# Generated by Django 4.2.1 on 2023-05-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Gender', models.CharField(max_length=2)),
                ('Birthtown', models.TextField()),
                ('birth_date', models.CharField(max_length=255)),
                ('Street', models.TextField()),
                ('Hometown', models.TextField()),
                ('Class', models.TextField()),
                ('start_date', models.DateField()),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
